

LOOKBACK_WEEKS_FOR_SCHEDULING = 15
NUM_FUTURE_WEEKS_SCHEDULE = LOOKBACK_WEEKS_FOR_SCHEDULING // 3

CLEANING_SCHEDULES_URL_PREFIX = "/cleaning_schedules"
MORE_INFO_URL_PREFIX = "/more_info"
BUTTONS_URL_PREFIX = "/buttons"
